#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.0.{build}

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
- Visual Studio 2019

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
before_build:
- ps: nuget restore .\GitExtensions.PluginTemplate.sln

build:
  # enable MSBuild parallel builds
  parallel: true
  # MSBuild verbosity level
  verbosity: minimal
